### ISSUE TITLE
Nested values eagerly validated for missing non-optional values

### ISSUE THREAD

**Issue by rpdasilva** [seanmay/io-guard#4]
Reduced test case:
https://stackblitz.com/edit/angular-bi2upg?file=src/app/app.service.ts

Data requested from https://jsonplaceholder.typicode.com/users
Explicitly setting `user.address` to undefined (or null) will produce a exception
`ERROR TypeError: Cannot read property 'street' of undefined`

Expected behaviour: No exception should be thrown - Guard should safely fail

Guard config:
```
export const isAddress = Guard<Address>({
  street: isStringWithLength,
  suite: isStringWithLength,
  city: isStringWithLength,
  zipcode: isStringWithLength,
  geo: erratic(isGeo)
});

export const isUser = Guard<User>({
  id: isNumber,
  name: isStringWithLength,
  username: isStringWithLength,
  email: isStringWithLength,
  address: isAddress,
  phone: isStringWithLength,
  website: erratic(isStringWithLength),
  company: erratic(isCompany)
});
```

**Comment by seanmay** [comment]
This is great! Thanks for the find.
I should be doing a `null|undefined` check at the top of `Guard`, and checking the array in `GuardEach`, to ensure that it is a valid array, though I suppose an extensive "isArraylike" would be useful at some point).

If I fail early, in those two spots, that should be the end of this bug.
Though, I will also have to add a section in the future docs about adding your own custom guards, in that it would be on you to either ensure your checks fail gracefully at the top, or be wrapped in another wrapper, which would ensure that nothing gets by, if `null|undefined`.

A bugfix, a doc requirement, and a potential feature, rolled into one issue!
